services:
  - type: web
    name: agroshop-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    disk:
      name: agroshop-db-storage
      mountPath: /data
      sizeGB: 1
